<a href="https://colab.research.google.com/github/mideade247/ProjectITC/blob/main/nlp_test_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Text Embeddings Using Universal Sentences Encoder**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow.keras as keras

In [ ]:
model_url = "https://tfhub.dev/google/universal-sentence-encoder/4"

In [ ]:
model = hub.load(model_url)

In [ ]:
def embed(input_text, embed_model = model):
  return embed_model(input_text)

In [ ]:
embeddings = embed(["This is a sentence"])

In [ ]:
embeddings[0].numpy()

array([ 0.02881767, -0.02020015,  0.01069628,  0.0385053 , -0.09253702,
        0.01752774, -0.04711751,  0.0478521 ,  0.01430713,  0.02635952,
        0.02157276, -0.04987606,  0.03023818,  0.11923701,  0.04333102,
       -0.11343763, -0.02569381,  0.00875983, -0.03205026, -0.03528893,
        0.065098  ,  0.07168703,  0.00487422, -0.00622953, -0.05483385,
        0.06636366,  0.02197697, -0.08987362,  0.03663914, -0.04186109,
        0.03020706, -0.02176558,  0.00683554, -0.04167067, -0.09498136,
       -0.03249762,  0.06278758,  0.04457697,  0.00825471, -0.02461435,
       -0.00744968,  0.00276056,  0.04595318,  0.0438056 , -0.06370507,
       -0.01170835, -0.05826195, -0.02410091, -0.035766  , -0.03617879,
       -0.01113707, -0.0866305 , -0.08743551,  0.00281444, -0.01570992,
       -0.04420159,  0.0287745 ,  0.03433856, -0.0100031 , -0.04693236,
        0.00529842, -0.05397878,  0.01005255, -0.01533142, -0.05143673,
       -0.01195163, -0.04800459,  0.02214861,  0.03110618, -0.01

**Semantic Similarity Scoring**

In [ ]:
from numpy.linalg import norm

In [ ]:
def cos_sim(A,B):
  return np.inner(A,B)/(norm(A)*norm(B))

def euclidean(A,B):
  return [norm(A-B)]

In [ ]:
def is_it_sim(textA, textB, thresh=0.28, sim_func = cos_sim):
  embeddingsA = embed([textA])
  embeddingsB =embed([textB])
  sim_score = sim_func(embeddingsA, embeddingsB)
  if sim_score > thresh:
    print("They are SIMILAR!")
  else:
    print("Not at all...")
  return sim_score,sim_score>thresh

In [ ]:
QuestionA = "This is a technology Company that builds computers"

AnswerA = "I had a delicious fruit called apple"
# AnswerB = "I am writing a program on my Apple laptop"
AnswerB = "My favorite PC is an HP"
#checking if they are match or not

In [ ]:
is_it_sim(QuestionA, AnswerB)

They are SIMILAR!


(array([[0.33259058]], dtype=float32), array([[ True]]))

In [ ]:
## Building into a classifier

In [ ]:
## we dont need a huge amout to build a classifier , it;s already fine tuned.

***Building Text Classification Using Embeddings and GUSE***

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow.keras as keras
import tf_keras

import tensorflow_datasets as tfds

In [ ]:
### we can set the train and test that we want in tensorflow datraset

Import Film Review dataset from TF dataset

In [ ]:
train_data, validation_data, test_data = tfds.load(
    name="imdb_reviews",
    split=('train[:60%]','train[60%:]','test'),
    as_supervised =True
)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/incomplete.YQIWU4_1.0.0/imdb_reviews-train.tfrecor…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/incomplete.YQIWU4_1.0.0/imdb_reviews-test.tfrecord…

Generating unsupervised examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/incomplete.YQIWU4_1.0.0/imdb_reviews-unsupervised.…

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [ ]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))

In [ ]:
train_examples_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [ ]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

## Load Hub data and create a hub Layer

In [ ]:
embedding_model_url = "https://tfhub.dev/google/universal-sentence-encoder/4"

In [ ]:
hub_layer = hub.KerasLayer(embedding_model_url, input_shape=[], dtype=tf.string, trainable=False)

## Build A Neural Net Text Classifier

In [ ]:
nlp_model = tf_keras.Sequential()

In [ ]:
nlp_model.add(hub_layer)
nlp_model.add(tf_keras.layers.Dense(256, activation ="relu"))
#add two dropout layers, just optional
nlp_model.add(tf_keras.layers.Dropout(0.1))

nlp_model.add(tf_keras.layers.Dense(128, activation ="relu"))
nlp_model.add(tf_keras.layers.Dropout(0.1))

nlp_model.add(tf_keras.layers.Dense(64, activation ="relu"))

nlp_model.add(tf_keras.layers.Dense(1, activation = "sigmoid"))    # adding sigmoid here is not nec needed


In [ ]:
nlp_model.summary()


Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 512)               256797824 
                                                                 
 dense_13 (Dense)            (None, 256)               131328    
                                                                 
 dropout_6 (Dropout)         (None, 256)               0         
                                                                 
 dense_14 (Dense)            (None, 128)               32896     
                                                                 
 dropout_7 (Dropout)         (None, 128)               0         
                                                                 
 dense_15 (Dense)            (None, 64)                8256      
                                                                 
 dense_16 (Dense)            (None, 1)                

## Compile ansd Train NLP

In [ ]:
nlp_model.compile(optimizer = tf_keras.optimizers.Adam(), loss=tf_keras.losses.BinaryCrossentropy(from_logits = False), metrics =["binary_accuracy"])

In [ ]:
history = nlp_model.fit(train_data.batch(512), epochs =5, validation_data=validation_data.batch(512), verbose =2)

Epoch 1/5
30/30 - 74s - loss: 0.5170 - binary_accuracy: 0.7881 - val_loss: 0.3660 - val_binary_accuracy: 0.8411 - 74s/epoch - 2s/step
Epoch 2/5
30/30 - 51s - loss: 0.3457 - binary_accuracy: 0.8515 - val_loss: 0.3330 - val_binary_accuracy: 0.8538 - 51s/epoch - 2s/step
Epoch 3/5
30/30 - 51s - loss: 0.3228 - binary_accuracy: 0.8621 - val_loss: 0.3294 - val_binary_accuracy: 0.8585 - 51s/epoch - 2s/step
Epoch 4/5
30/30 - 51s - loss: 0.3138 - binary_accuracy: 0.8678 - val_loss: 0.3294 - val_binary_accuracy: 0.8575 - 51s/epoch - 2s/step
Epoch 5/5
30/30 - 51s - loss: 0.3036 - binary_accuracy: 0.8737 - val_loss: 0.3266 - val_binary_accuracy: 0.8597 - 51s/epoch - 2s/step


### Model Evaluation

In [ ]:
results = nlp_model.evaluate(test_data.batch(512), verbose =2)

49/49 - 52s - loss: 0.3288 - binary_accuracy: 0.8564 - 52s/epoch - 1s/step


## Model Saving in TensorFlow

In [ ]:
nlp_model.save("/content/drive/MyDrive/Dataset/nlp_model")

### Inference Function

In [ ]:
def get_sentiment(text, model=nlp_model, thresh=0.5):
  p_hat =model.predict([text])[0][0]
  out = (p_hat>thresh).astype('int32')

  print("Vievwer Comment:\n"+text+"\n\n The Review was:")
  if out: print(" It was Good!")
  else: print("Bad Movie!")
  return p_hat


In [ ]:
get_sentiment("It was Dynamite! Will see again, and again, if I wanted to barf a lot!")

1/1 [==============================] - 1s 570ms/step
Vievwer Comment:
It was Dynamite! Will see again, and again, if I wanted to barf a lot!

 The Review was:
Bad Movie!


np.float32(0.1278652)

In [ ]:
get_sentiment("Few times in my life a movie makes me think about the truth and hardship in the world")

1/1 [==============================] - 0s 46ms/step
Vievwer Comment:
Few times in my life a movie makes me think about the truth and hardship in the world

 The Review was:
Bad Movie!


np.float32(0.48726508)

In [ ]:
get_sentiment("The love I know")

1/1 [==============================] - 0s 45ms/step
Vievwer Comment:
The love I know

 The Review was:
 It was Good!


np.float32(0.9209706)

In [ ]:
get_sentiment("Baba Suwe")

1/1 [==============================] - 0s 44ms/step
Vievwer Comment:
Baba Suwe

 The Review was:
 It was Good!


np.float32(0.7457381)